# scene
scene: building
model_id: Rs
is_interactive: false
build_graph: true
load_texture: true
trav_map_resolution: 0.1
trav_map_erosion: 2

# robot
robot: Locobot
is_discrete: false
linear_velocity: 0.5
angular_velocity: 1.5707963267948966

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching
target_dist_min: 1.0
target_dist_max: 10.0
initial_pos_z_offset: 0.1
additional_states_dim: 4

# reward
reward_type: geodesic
success_reward: 10.0
slack_reward: -0.01
potential_reward_weight: 1.0
collision_reward_weight: -0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500
goal_format: polar

# sensor spec
output: [sensor, rgb, depth]
# image
# Intel® RealSense™ Depth Camera D435
# https://store.intelrealsense.com/buy-intel-realsense-depth-camera-d435.html
fisheye: false
image_width: 160
image_height: 90
vertical_fov: 42.5
# depth
depth_low : 0.1
depth_high: 10.0

# sensor noise
depth_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false

